<a href="https://colab.research.google.com/github/PriyankaSharma0925/MachineLearning/blob/main/ManipulatingTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf



In [2]:
tensor_1=tf.constant([1,2,3,4,5,6,7,8,9], shape=(3,3))
tensor_1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [3]:
tensor_1 + 3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [4]:
tensor_1* 2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>

In [6]:
tf.multiply(tensor_1 , 2)

            

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>

In [8]:
tf.multiply(tensor_1,tensor_1) # this will do element by element multiplication

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)>

In [7]:
tf.add(tensor_1,10)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]], dtype=int32)>

In [9]:
# In ML matrix multiplicatin is one of the most common operation
tf.matmul(tensor_1,tensor_1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

In [13]:
reshapedTensor=tf.reshape(tensor_1,shape=(1,9))

In [15]:
reshapedTensor.numpy()

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [16]:
tf.transpose(tensor_1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int32)>