<a href="https://colab.research.google.com/github/PriyankaSharma0925/MachineLearning/blob/main/TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
scaler=tf.constant(5)

In [3]:
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [22]:
vector=tf.constant([4,0,5,6,7,8,8,3])

In [5]:
vector

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [6]:
matrix=tf.constant([[2]])

In [7]:
matrix

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[2]], dtype=int32)>

In [30]:
tensor=tf.constant([[[4,5],
                     [6,7]],
                    [[5,6],
                     [8,9]]])

In [31]:
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[4, 5],
        [6, 7]],

       [[5, 6],
        [8, 9]]], dtype=int32)>

In [32]:
scaler.ndim,vector.ndim,matrix.ndim,tensor.ndim

(0, 1, 2, 3)

In [18]:
tf.rank(scaler),tf.rank(scaler),tf.size(scaler)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [23]:
tf.rank(vector),tf.rank(vector),tf.size(vector)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [35]:
tf.shape(matrix),tf.rank(matrix),tf.size(matrix)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [34]:
tf.shape(tensor),tf.rank(tensor),tf.size(tensor)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [42]:
tf.random.set_seed(42)
rand_tensor1=tf.random.uniform(minval=0,maxval=1,shape=(5,300),seed=9)
rand_tensor1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.79607403, 0.49815786, 0.67241085, ..., 0.09477329, 0.7157892 ,
        0.17522621],
       [0.35869956, 0.6887872 , 0.9754571 , ..., 0.9076134 , 0.01819432,
        0.12533224],
       [0.9073261 , 0.92021954, 0.82361233, ..., 0.17835736, 0.3678484 ,
        0.14013803],
       [0.9498466 , 0.36302173, 0.0013175 , ..., 0.6793394 , 0.81695974,
        0.976863  ],
       [0.97967577, 0.5972265 , 0.90829945, ..., 0.65950596, 0.79918766,
        0.8568859 ]], dtype=float32)>

In [43]:
rand_tensor1.numpy()

array([[0.79607403, 0.49815786, 0.67241085, ..., 0.09477329, 0.7157892 ,
        0.17522621],
       [0.35869956, 0.6887872 , 0.9754571 , ..., 0.9076134 , 0.01819432,
        0.12533224],
       [0.9073261 , 0.92021954, 0.82361233, ..., 0.17835736, 0.3678484 ,
        0.14013803],
       [0.9498466 , 0.36302173, 0.0013175 , ..., 0.6793394 , 0.81695974,
        0.976863  ],
       [0.97967577, 0.5972265 , 0.90829945, ..., 0.65950596, 0.79918766,
        0.8568859 ]], dtype=float32)

In [44]:
rand_tensor_2=tf.random.uniform(minval=0,maxval=1,shape=(5,300),seed=9)
rand_tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.75724185, 0.78385365, 0.17958641, ..., 0.5497    , 0.07608819,
        0.22292292],
       [0.38637543, 0.95431244, 0.32342255, ..., 0.43897283, 0.15580821,
        0.427588  ],
       [0.9104581 , 0.5605484 , 0.972301  , ..., 0.36840487, 0.7113105 ,
        0.6113094 ],
       [0.9526664 , 0.18419755, 0.5925083 , ..., 0.04861462, 0.46683216,
        0.6769749 ],
       [0.266294  , 0.91047835, 0.6088846 , ..., 0.383834  , 0.02093661,
        0.20421195]], dtype=float32)>

In [45]:
tf.matmul(rand_tensor1,rand_tensor_2)

InvalidArgumentError: ignored