<a href="https://colab.research.google.com/github/PriyankaSharma0925/MachineLearning/blob/main/TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [4]:
scaler=tf.constant(5)

In [5]:
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [6]:
vector=tf.constant([4,0,5,6,7,8,8,3])

In [7]:
vector

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([4, 0, 5, 6, 7, 8, 8, 3], dtype=int32)>

In [8]:
matrix=tf.constant([[2]])

In [9]:
matrix

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[2]], dtype=int32)>

In [10]:
tensor=tf.constant([[[4,5],
                     [6,7]],
                    [[5,6],
                     [8,9]]])

In [11]:
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[4, 5],
        [6, 7]],

       [[5, 6],
        [8, 9]]], dtype=int32)>

In [12]:
scaler.ndim,vector.ndim,matrix.ndim,tensor.ndim

(0, 1, 2, 3)

In [13]:
tf.rank(scaler),tf.rank(scaler),tf.size(scaler)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [14]:
tf.rank(vector),tf.rank(vector),tf.size(vector)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [15]:
tf.shape(matrix),tf.rank(matrix),tf.size(matrix)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [16]:
tf.shape(tensor),tf.rank(tensor),tf.size(tensor)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [17]:
tf.random.set_seed(42)
rand_tensor1=tf.random.uniform(minval=0,maxval=1,shape=(5,300),seed=9)
rand_tensor1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.79607403, 0.49815786, 0.67241085, ..., 0.09477329, 0.7157892 ,
        0.17522621],
       [0.35869956, 0.6887872 , 0.9754571 , ..., 0.9076134 , 0.01819432,
        0.12533224],
       [0.9073261 , 0.92021954, 0.82361233, ..., 0.17835736, 0.3678484 ,
        0.14013803],
       [0.9498466 , 0.36302173, 0.0013175 , ..., 0.6793394 , 0.81695974,
        0.976863  ],
       [0.97967577, 0.5972265 , 0.90829945, ..., 0.65950596, 0.79918766,
        0.8568859 ]], dtype=float32)>

In [18]:
rand_tensor1.numpy()

array([[0.79607403, 0.49815786, 0.67241085, ..., 0.09477329, 0.7157892 ,
        0.17522621],
       [0.35869956, 0.6887872 , 0.9754571 , ..., 0.9076134 , 0.01819432,
        0.12533224],
       [0.9073261 , 0.92021954, 0.82361233, ..., 0.17835736, 0.3678484 ,
        0.14013803],
       [0.9498466 , 0.36302173, 0.0013175 , ..., 0.6793394 , 0.81695974,
        0.976863  ],
       [0.97967577, 0.5972265 , 0.90829945, ..., 0.65950596, 0.79918766,
        0.8568859 ]], dtype=float32)

In [19]:
rand_tensor_2=tf.random.uniform(minval=0,maxval=1,shape=(5,300),seed=9)
rand_tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.75724185, 0.78385365, 0.17958641, ..., 0.5497    , 0.07608819,
        0.22292292],
       [0.38637543, 0.95431244, 0.32342255, ..., 0.43897283, 0.15580821,
        0.427588  ],
       [0.9104581 , 0.5605484 , 0.972301  , ..., 0.36840487, 0.7113105 ,
        0.6113094 ],
       [0.9526664 , 0.18419755, 0.5925083 , ..., 0.04861462, 0.46683216,
        0.6769749 ],
       [0.266294  , 0.91047835, 0.6088846 , ..., 0.383834  , 0.02093661,
        0.20421195]], dtype=float32)>

In [20]:
tf.matmul(rand_tensor1,tf.transpose(rand_tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[77.9325  , 79.077835, 75.89861 , 81.09679 , 70.85812 ],
       [79.7024  , 80.11417 , 80.71191 , 82.16049 , 72.75039 ],
       [77.475586, 80.45766 , 78.93689 , 81.65938 , 73.81871 ],
       [75.87905 , 75.77568 , 75.45163 , 77.181404, 70.83116 ],
       [78.36458 , 81.13037 , 79.61514 , 81.42276 , 72.49864 ]],
      dtype=float32)>

In [25]:
tf.tensordot(rand_tensor1,tf.transpose(rand_tensor_2),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[77.9325  , 79.077835, 75.89861 , 81.09679 , 70.85812 ],
       [79.7024  , 80.11417 , 80.71191 , 82.16049 , 72.75039 ],
       [77.475586, 80.45766 , 78.93689 , 81.65938 , 73.81871 ],
       [75.87905 , 75.77568 , 75.45163 , 77.181404, 70.83116 ],
       [78.36458 , 81.13037 , 79.61514 , 81.42276 , 72.49864 ]],
      dtype=float32)>

In [27]:
tf.random.set_seed(42)
rand_tensor3=tf.random.uniform(minval=0,maxval=1,shape=(224, 224, 3), seed=42)
#rand_tensor4=tf.random.uniform(minval=0,maxval=1,shape=(224, 224, 3), seed=2)

In [29]:
rand_tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.4163028 , 0.26858163, 0.47968316],
        [0.36457133, 0.95471144, 0.9418646 ],
        [0.61483395, 0.35842144, 0.5936024 ],
        ...,
        [0.3001454 , 0.7371932 , 0.9997108 ],
        [0.6578264 , 0.79280615, 0.1523186 ],
        [0.18333101, 0.84532166, 0.66058433]],

       [[0.99603903, 0.74609745, 0.5254276 ],
        [0.97391105, 0.12732589, 0.33558083],
        [0.15509152, 0.3798263 , 0.02595055],
        ...,
        [0.24695694, 0.4792341 , 0.907869  ],
        [0.93202424, 0.21663308, 0.3452747 ],
        [0.01570225, 0.97835445, 0.10668027]],

       [[0.216218  , 0.02733779, 0.2472924 ],
        [0.56103206, 0.02278149, 0.83240056],
        [0.8430499 , 0.86110675, 0.39599562],
        ...,
        [0.51704574, 0.2421813 , 0.6224375 ],
        [0.52620804, 0.409366  , 0.84243226],
        [0.5460491 , 0.18278158, 0.9165064 ]],

       ...,

       [[0.74593174, 0.8235165 , 0.39988327],
        [0.58

In [33]:
tf.reduce_max(rand_tensor3)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999901>

In [35]:
tf.reduce_min(rand_tensor3)

<tf.Tensor: shape=(), dtype=float32, numpy=1.7404556e-05>